### ISSUE TITLE
Catchup with latest API updates

### ISSUE THREAD

**Issue by jofftiquez** [jofftiquez/paymongo#10]
Refer to [next version](https://github.com/jofftiquez/paymongo/projects/1)

**Comment by jofftiquez** [comment]
Hello! Thank you for submitting an issue.

**Comment by ccfiel** [comment]
@jofftiquez when will this feature available? :)

**Comment by jofftiquez** [comment]
@ccfiel now that there's someone interested I might expedite the ETA. I thinking, tomorrow, in-time for Easter Sunday. :)

**Comment by ccfiel** [comment]
@jofftiquez wow! thanks for the update! :)

**Comment by jofftiquez** [comment]
Hello @ccfiel the latest updates are now available in this branch [feat/next](https://github.com/jofftiquez/paymongo/tree/feat/next).

Tests are all passing. I will merge this soon today as soon the docs are done. 

There has been some major changes in the syntax of using the `paymongo` instance. I decided to mimic the Stripe's node.js library pattern. E.g. `stripe.subscriptions.create()`

Altho the docs are not yet completed, you can test the build in the `./dist` folder. For your convenience here are all the available available methods. 

```javascript
const paymongo = new Paymongo(process.env.secret);

// Payment Methods
paymongo.paymentMethods.create(data);
paymongo.paymentMethods.retrieve(id);

// Payment Intents
paymongo.paymentIntents.create(data);
paymongo.paymentIntents.retrieve(id);
paymongo.paymentIntents.attach(id, data);

// Sources
paymongo.sources.create(data);

// Payments
paymongo.payments.create(data);
paymongo.payments.retrieve(id);
paymongo.payments.list();

// Tokens (DEPRECATED)
paymongo.tokens.create(data);
paymongo.tokens.retrieve(id);

// Webhooks
paymongo.webhooks.create(data);
paymongo.webhooks.retrieve(id);
paymongo.webhooks.list();
paymongo.webhooks.toggle(id, action); // action = 'enable' or 'disable'
```

**Comment by ccfiel** [comment]
@jofftiquez wow that was fast! thanks! I will test it

**Comment by jofftiquez** [comment]
@ccfiel btw it's already release try `v1.0.0`

**Comment by ccfiel** [comment]
Thanks! 😀
