### ISSUE TITLE
Can't access documentation

### ISSUE THREAD

**Issue by dsmalicsi** [jofftiquez/paymongo#55]
Hi @jofftiquez and the team maintaining this repo

First, thank you for your great work on this library. I noticed that the documentation link [https://paymongo.ossph.org/](url) is currently down. I hope you can check on this. Having access to the documentation would greatly assist me and others who are using your library.

Thanks for your help!

![image](https://github.com/OSSPhilippines/paymongo/assets/6241711/f4635a0b-64f9-4c27-be95-de80e84c34b7)

**Comment by jofftiquez** [comment]
Hi, thank you for reporting this. It looks like GitBook disconnected the previous DNS setup. I reconnected it, it should working again now.

**Comment by jofftiquez** [comment]
Closing this issue now thanks. 

See the website here: https://paymongo.ossph.org/
